version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout

      - run: cd src/lang/nodejs && npm install && npx eslint src/index.js && npm test src/index.test.js
