name: Go CI
on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "src/lang/go/*"
  pull_request:
    paths:
      - ".github/workflows/go.yml"
      - "src/lang/go/*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/lang/go/src/blotjson
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.0
        with:
          go-version: ^1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build .

      - name: Test
        run: go test -v .
