name: Go CI
on:
  push:
    paths:
      - ".github/workflows/go.yml"
      - "src/lang/go/*"
  pull_request:
    paths:
      - ".github/workflows/go.yml"
      - "src/lang/go/*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/lang/go
          
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.0
        with:
          go-version: ^1.13

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
        
