name: Go CI

on:
  push:
    paths:
      - "src/lang/go/github.com/arsalanc-v2/blotjson"
  pull_request:
    paths:
      - "src/lang/go/github.com/arsalanc-v2/blotjson"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/lang/go
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .
