name: Nodejs CI Build

# Trigger build on push and pull requests
on:
  push:
    paths:
      - ".github/workflows/nodejs.yml"
      - "src/lang/nodejs/*"
  pull_request:
    paths:
      - ".github/workflows/nodejs.yml"
      - "src/lang/nodejs/*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/lang/nodejs

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/clover.xml
